### ISSUE TITLE
Push master builds to docker hub in CI

### ISSUE THREAD

**Issue by cmyui** [osuAkatsuki/bancho.py#514]
We have a public repo here: https://hub.docker.com/r/osuakatsuki/bancho.py

Make a CI workflow which builds & deploys to this.

Basically:
```yaml
- name: Set up QEMU
  uses: docker/setup-qemu-action@v2

- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v2

- name: Login to Docker Hub
  uses: docker/login-action@v3
  with:
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}

- name: Build and push
  uses: docker/build-push-action@v4
  with:
    context: .
    push: true
    tags: osuakatsuki/bancho.py:latest
    cache-from: type=gha
    cache-to: type=gha,mode=max
```
